version: "3"
services:
    app:
        container_name: app
        build: .
        ports:
            - "0.0.0.0:1213:1213"
        environment:
            - STAGE=TEST
            - PORT=1213
        entrypoint: 
            - ./main
