version: "3"
services:
    app:
        container_name: app
        build: .
        ports:
            - "0.0.0.0:8080:8080"
        environment:
            - STAGE=TEST
            - PORT=8080
        entrypoint: 
            - ./main
