// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contest struct {
	IsRated           bool   `json:"isRated"`
	Place             int    `json:"place"`
	OldRating         int    `json:"oldRating"`
	NewRating         int    `json:"newRating"`
	Performance       int    `json:"performance"`
	InnerPerformance  int    `json:"innerPerformance"`
	ContestScreenName string `json:"contestScreenName"`
	ContestName       string `json:"contestName"`
	ContestNameEn     string `json:"contestNameEn"`
	EndTime           string `json:"endTime"`
	IsParticipated    bool   `json:"isParticipated"`
}
