// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contest struct {
	IsRated           bool   `json:"isRated"`
	Place             int    `json:"place"`
	ActualOldRating   int    `json:"actualOldRating"`
	ActualNewRating   int    `json:"actualNewRating"`
	Performance       int    `json:"performance"`
	InnerPerformance  int    `json:"innerPerformance"`
	ContestScreenName string `json:"contestScreenName"`
	ContestName       string `json:"contestName"`
	ContestNameEn     string `json:"contestNameEn"`
	EndTime           string `json:"endTime"`
	OptimalOldRating  int    `json:"optimalOldRating"`
	OptimalNewRating  int    `json:"optimalNewRating"`
	IsParticipated    bool   `json:"isParticipated"`
}
